#!/bin/bash

set -e

FIND_IMAGE_COMMAND="sxiv -t -o"
SEARCH_ROOT=(
    /usr/share/backgrounds
    ~/Pictures/wallpaper
)

change-wallpaper(){
    wal -n -i "$@"
    feh --bg-scale "$(< "${HOME}/.cache/wal/wal")"
}


wallpaper=$(${FIND_IMAGE_COMMAND} "${SEARCH_ROOT[@]}")
change-wallpaper "${wallpaper}"
notify-send "Changing Wallpaper to ${wallpaper}"
