#!/bin/bash
[[ $(cat /proc/1/comm) == "systemd" ]] && logind=systemctl || logind=loginctl

set_menu() {
    if command -v rofi; then
        MENU="rofi -p exit> -dmenu"
    else
        MENU="dmenu"
    fi
}

set_exit_command() {
    if pgrep qtile > /dev/null; then
        EXIT_COMMAND="qtile cmd-obj -o cmd -f shutdown"
    fi
}

set_lock_command() {
    if [[ -z $HYPRLAND_INSTANCE_SIGNATURE ]]; then
        lock_cmd=blurlock
    else
        lock_cmd=hyprlock
    fi
}

options=(
    lock
    suspend
    hibernate
    logout
    reboot
    shutdown
)

main() {
    set_menu
    set_exit_command 
    set_lock_command 

    selected=$(printf "%s\n" "${options[@]}" | $MENU)

    case "$selected" in
        lock)
            $lock_cmd
            ;;
        suspend)
            $lock_cmd && $logind suspend
            ;;
        hibernate)
            $lock_cmd && $logind hibernate
            ;;
        logout)
            $EXIT_COMMAND
            ;;
        reboot)
            $logind reboot
            ;;
        shutdown)
            $logind poweroff
            ;;
        *)
            notify-send "Custom Exit" "Invalid Argument" "Try again with: lock | suspend | hibernate | reboot | shutdown"
            exit 2
    esac

    exit 0
}

main
