#!/bin/bash
[[ $(cat /proc/1/comm) == "systemd" ]] && logind=systemctl || logind=loginctl

if command -v wofi; then
    MENU="wofi -p exit> -dmenu"
elif command -v rofi; then
    MENU="rofi -p exit> -dmenu"
else
    MENU="dmenu"
fi

if [[ -z $HYPRLAND_INSTANCE_SIGNATURE ]]; then
    lock_cmd=blurlock
else
    lock_cmd=hyprlock
fi

options=(
    lock
    suspend
    hibernate
    reboot
    shutdown
)

selected=$(printf "%s\n" "${options[@]}" | $MENU)

case "$selected" in
    lock)
        $lock_cmd
        ;;
    suspend)
        $lock_cmd && $logind suspend
        ;;
    hibernate)
        $lock_cmd && $logind hibernate
        ;;
    reboot)
        $logind reboot
        ;;
    shutdown)
        $logind poweroff
        ;;
    *)
        notify-send "Custom Exit" "Invalid Argument" "Try again with: lock | suspend | hibernate | reboot | shutdown"
        exit 2
esac

exit 0
