#!/bin/bash

HDMI_CONNECTED=$(xrandr | grep HDMI | cut -d ' ' -f 2) 
HDMI_PORT=$(xrandr | grep HDMI | cut -d ' ' -f 1) 

if [[ "$HDMI_CONNECTED" == 'connected' ]]; then
    xrandr --output eDP-1 --off --output $HDMI_PORT --primary --mode 3440x1440 --pos 0x0 --rotate normal
else
    xrandr --auto
fi

feh --bg-scale $HOME/Pictures/wallpaper/current_wallpaper.jpg
