#!/bin/bash

HDMI_CONNECTED=$(xrandr | grep HDMI | cut -d ' ' -f 2) 

if [[ "$HDMI_CONNECTED" == 'connected' ]]; then
    xrandr --output eDP-1 --off --output HDMI-1 --primary --mode 3440x1440 --pos 0x0 --rotate normal
fi
