#!/usr/bin/env bash

# Função para exibir a mensagem de ajuda
function show_help() {
	echo "Usage: qconf [-r|-f] [command] [search_term]"
	echo ""
	echo "Options:"
	echo "  -r          Use 'rg' (ripgrep) for searching (default is 'fd' for file search)"
	echo "  -h          Show this help message"
	echo ""
	echo "Arguments:"
	echo "  [command]   Command to execute on selected file"
	echo "  [search_term] Tag to search for (optional, prompted if not provided)"
	exit 0
}

# Variáveis padrão
SEARCH_TOOL="fd -E .git -t f -H -p --ignore-file ~/.config/qconf/ignore.list"
PREVIEW_COMMAND="bat --color=always {1}"
CONFIG_PATHS="$CONFIG_PATH $DOTFILES_PATH"
FZF_FLAGS="--tmux center,80%"

# Parse das flags
while getopts "rnh" opt; do
	case $opt in
	r)
		SEARCH_TOOL="rg --with-filename --line-number --column --smart-case --hidden --ignore-file ~/.config/qconf/ignore.list" PREVIEW_COMMAND="bat --color=always {1} --highlight-line {2}"
		;;
	n)
		FZF_FLAGS=""
		;;
	h)
		show_help
		;;
	*)
		show_help
		;;
	esac
done

# Remover as flags dos parâmetros passados
shift $((OPTIND - 1))

# Recebe o segundo argumento ou solicita a busca ao usuário
if [[ -z $2 ]]; then
	read -p "Search Config: " doc_tag
else
	doc_tag=$2
fi

# Recebe o primeiro argumento ou solicita a seleção ao usuário via fzf
if [[ -z $1 ]]; then
	selected=$(cat ~/.config/qconf/output_command.list | fzf "${FZF_FLAGS}")
else
	selected="$1"
fi

# Execução do fzf com os comandos configurados
fzf --ansi --disabled ${FZF_FLAGS} --query "$doc_tag" \
	--reverse \
	--bind "start:reload:$SEARCH_TOOL {q} $CONFIG_PATHS" \
	--bind "change:reload:sleep 0.1; $SEARCH_TOOL {q} $CONFIG_PATHS || true" \
	--delimiter : \
	--preview "$PREVIEW_COMMAND" \
	--preview-window 'up,60%,border-bottom,+{2}+3/3,~3' \
	--bind "enter:become($selected {1})"
