#!/usr/bin/env bash

if [[ -z $1 ]]; then
    read -p "Search Config: " doc_tag
else
    doc_tag=$1
fi

selected=`cat ~/.config/qconf/output_command.list | fzf`;

fd -p $doc_tag ~/.dotfiles ~/.config -E .git -t f -H | fzf --reverse | xargs $selected

