#!/usr/bin/env bash

# Inspired by The Primeagen's tmux-sessionizer
# https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer

DEFAULT_VALUE='Create New Session'
FIND_ROOT=~/Documents
INPUT_PATH=$1

if [[ $# -eq 1 ]]; then
    selected_session=$1
else
    session_list="$(tmux list-sessions)\n$DEFAULT_VALUE"
    selected_name=$(\
        echo -e "$session_list" | \
        fzf --reverse | \
        sed '/^$/d' | \
        cut -d':' -f1 
    )
fi

if [[ $selected_name == $DEFAULT_VALUE ]]; then 

    selected_session=$(find $FIND_ROOT  -maxdepth 3 -type d | fzf --reverse)

    if [[ -z $selected_session ]]; then
        exit 0
    fi
fi

 if ! [[ -z $INPUT_PATH ]] || [[ $selected_name == $DEFAULT_VALUE ]]; then
    selected_name=$(basename "$selected_session" | tr . _)

    if ! tmux has-session -t=$selected_name 2> /dev/null; then
        # Create new detached tmux session
        tmux new-session -ds $selected_name -c $selected_session
    fi
fi
echo $selected_name $selected_session
if [[ -z $TMUX ]]; then
    tmux attach -t $selected_name
else
    tmux switch-client -t $selected_name
fi
