#!/bin/bash

if pgrep -x hypridle > /dev/null; then
    killall hypridle
    notify-send "Toggle-hypridle" "Stop Hypridle"
else
    hypridle &
    notify-send "Toggle-hypridle" "Starting Hypridle"
fi
